### ISSUE TITLE
remember() not querying the cache if I'm using ->first() after rather than ->get()

### ISSUE THREAD

**Issue by AntoninG** [DarkGhostHunter/RememberableQuery#12]
Hi,

I'm encountering a weird behaviour when I'm not using `->get()` after the `->remember()` method.
Example:
```
FacebookPageMetrics::withoutGlobalScopes()
    ->socialProfile($this->socialProfile->id)
    ->latest('date')
    ->remember(now()->addMinutes(30))
    ->first();
```

If I'm executing this twice in a row, the same key cache is generated `dump($this->cacheKey);` inside `\DarkGhostHunter\RememberableQuery\RememberableQuery::__construct` but the dumps of `DB::getQueryLog()` show this:

```
// dump($this->cacheKey);
"query|VL4KpSLHaRy258u4p9ZUcA=="
"query|VL4KpSLHaRy258u4p9ZUcA=="

// Query logs
array:2 [
  0 => "select * from`facebook_page_metrics` where `social_profile_id` = ? order by `date` desc limit 1" // hash "query|VL4KpSLHaRy258u4p9ZUcA=="
  1 => "select * from`facebook_page_metrics` where `social_profile_id` = ? order by `date` desc limit 1" // hash "query|VL4KpSLHaRy258u4p9ZUcA=="
]
```

So the query is executed twice and the cache is not used.
Any idea ?

**Comment by AntoninG** [comment]
But it works perfectly with 
```
FacebookPageMetrics::withoutGlobalScopes()
    ->socialProfile($this->socialProfile->id)
    ->latest('date')->limit(1)
    ->remember(now()->addMinutes(30))
    ->get()->first();
```

**Comment by DarkGhostHunter** [comment]
Wweeeeiiirrrd. I'll make a test for that.

Weird considering the result is not a builder instance.

**Comment by DarkGhostHunter** [comment]
It's working on my end, I'm unable to reproduce it.

Does the cache key exists after the first call? Because the behind the veil a `remember()` method is called from the Cache, which will run only if the cache key doesn't exists or has expired.
