### ISSUE TITLE
[BUG] Not working for paginated queries

### ISSUE THREAD

**Issue by Kladislav** [DarkGhostHunter/RememberableQuery#14]

**Comment by DarkGhostHunter** [comment]
Couldn't reproduce.

**Comment by Kladislav** [comment]
Sorry, its not working "out of the box", because it requires to append page number from request to custom key, i do it myself, so maybe it will be good idea to add support for paginated queries as a feature in future releases

**Comment by DarkGhostHunter** [comment]
> Sorry, its not working "out of the box", because it requires to append page number from request to custom key, i do it myself, so maybe it will be good idea to add support for paginated queries as a feature in future releases 😉

Oh, snap!

It's a tricky situation to use with `beforeQuery()`. Not too long ago, when I made this package, I encountered a roadblock where this would get me into a loop. I'll try again so in a major version the key generated reflects the final query, which will include pagination data.
