### ISSUE TITLE
feature to remove cache for model and on event model

### ISSUE THREAD

**Issue by mohamedsharaf** [DarkGhostHunter/RememberableQuery#8]
feature to remove the cache for model 

also, register an event to remove cache on  model

**Comment by DarkGhostHunter** [comment]
Can you elaborate? If you don't want to remember a query, you can just not call the method. In the other hand, you can use `when()` to programmatically remember a query.

**Comment by mohamedsharaf** [comment]
add a method to delete cache

 example usage
I will return cached query till new record created

on creating new model i will call the cache delete method on that model

**Comment by DarkGhostHunter** [comment]
That's out of the scope of this package.
